export const FETCH_BANNER = 'FETCH_BANNER'
export const STOP_FETCH_BANNER = 'STOP_FETCH_BANNER'

export const FETCH_RECOMMEND = 'FETCH_RECOMMEND'
export const STOP_FETCH_RECOMMEND = 'STOP_FETCH_RECOMMEND'
