export const BANNER = 'banner'
export const CHANNEL_LIST = 'channelList'
export const CATALOG = 'catalog'
export const BREEZE_DAILY_LIST = 'breezeDaily'
export const USER_LOGIN = 'userLogin'
export const PRODUCT_INFO = 'productInfo'
